GET http://localhost:5063/games
###
GET http://localhost:5063/games/83e83d7d-8df1-4b7a-8c12-dc11f27ff4c8
###
POST http://localhost:5063/games
Content-Type: application/json

{
  "name": "The Legend of Zelda: Breath of the Wild",
  "price": 59.99,
  "releaseDate": "2017-03-03"
}
###
PUT http://localhost:5063/games/5869793f-cb75-4f8b-b798-a510462f8d5d
Content-Type: application/json

{
  "price": 9.99
}