GET http://localhost:5063/games
###
GET http://localhost:5063/games/DD3E52BE-D661-41AE-8BE9-DA3A16000F85
###
POST http://localhost:5063/games
Content-Type: application/json

{
  "name": "Terraria",
  "genreId": 2,
  "price": 19.99,
  "releaseDate": "2017-03-03"
}
###
PUT http://localhost:5063/games/DD3E52BE-D661-41AE-8BE9-DA3A16000F85
Content-Type: application/json

{
  "name": "Terraria",
  "genreId": 2,
  "price": 9.99,
  "releaseDate": "2017-03-03"
}
###
DELETE http://localhost:5063/games/47160d1b-8341-416f-9b6f-070653f70414